# Generated by Django 4.2.5 on 2023-09-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_semana_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.empresa'),
        ),
    ]
