# Generated by Django 4.2.5 on 2023-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_semana_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseprocesso',
            name='NC',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='Não', max_length=3),
        ),
    ]
