# Generated by Django 4.2.5 on 2023-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_alter_analiseprocesso_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='numeroNC',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analiseprocesso',
            name='NC',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
