# Generated by Django 4.2.5 on 2023-09-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ip',
        ),
    ]
