# Generated by Django 4.2.5 on 2023-09-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('reponsavelCompra', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('empresaContratada', models.CharField(max_length=50)),
                ('responsavelAnuencia', models.CharField(max_length=50)),
                ('integridade', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Se os mesmo estão íntegros, bem lacrados nas suas embalagens e funcionando:', max_length=20, null=True)),
                ('requisitosNorma', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Se o mesmo cumpre os requisitos da norma, para qual foi comprado:', max_length=20, null=True)),
                ('metodologia', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Verificar se foi usada a metodologia correta na calibração:', max_length=20, null=True)),
                ('requisitos', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Verificar atendimento aos requisitos solicitados:', max_length=20, null=True)),
                ('calibracao', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Verificar se o equipamento calibrado foi aprovado', max_length=20, null=True)),
                ('observacoes', models.TextField(help_text='Observações', null=True)),
            ],
        ),
    ]
