# Generated by Django 4.2.5 on 2023-09-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compras',
            new_name='Compraaaaas',
        ),
    ]
