# Generated by Django 4.2.5 on 2023-09-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_rename_compraaaaas_compras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Comp',
        ),
    ]
