# Generated by Django 4.2.5 on 2023-09-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_compras_comp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comp',
            new_name='Compra',
        ),
    ]
