# Generated by Django 4.2.5 on 2023-09-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_rename_comp_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(),
        ),
    ]
