# Generated by Django 4.2.5 on 2023-09-25 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_compra_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='reponsavelCompra',
            new_name='responsavelCompra',
        ),
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 24)),
        ),
    ]
