# Generated by Django 4.2.5 on 2023-10-04 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_compra_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2023, 10, 4, 0, 28, 19, 379537, tzinfo=datetime.timezone.utc)),
        ),
    ]
