# Generated by Django 4.2.5 on 2023-09-25 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_reponsavelcompra_compra_responsavelcompra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 25)),
        ),
    ]
