# Generated by Django 4.2.5 on 2023-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_compra_options_alter_compra_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='labRBC',
            field=models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Verificar se o certificado foi feito por laboratório da RBC:', max_length=20, null=True),
        ),
    ]
