# Generated by Django 4.2.5 on 2023-09-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_empresa_alter_userprofile_empresa'),
        ('compras', '0009_compra_labrbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='responsavelCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.userprofile'),
        ),
    ]
