# Generated by Django 4.2.5 on 2023-09-25 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_compra_responsavelcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 18, 29, 48, 515545, tzinfo=datetime.timezone.utc)),
        ),
    ]
