# Generated by Django 4.2.5 on 2023-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_compra_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='dataRecebimento',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='labRBC',
            field=models.CharField(choices=[('A', 'A'), ('R', 'R'), ('NA', 'NA')], default='A', help_text='Verificar se o certificado foi feito por laboratório da RBC:', max_length=20, null=True, verbose_name='Laboratório RBC'),
        ),
    ]
