# Generated by Django 4.2.5 on 2023-09-26 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_alter_compra_datarecebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 9, 26, 12, 37, 34, 211226, tzinfo=datetime.timezone.utc)),
        ),
    ]
