# Generated by Django 4.2.5 on 2023-09-26 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_alter_compra_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2023, 9, 26, 12, 38, 34, 127014, tzinfo=datetime.timezone.utc)),
        ),
    ]
