# Generated by Django 4.2.5 on 2023-09-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_empresa_alter_userprofile_empresa'),
        ('analiseProcessos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.empresa'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
