# Generated by Django 4.2.5 on 2023-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiseProcessos', '0004_alter_questao_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormularioRespondido',
            new_name='AnaliseProcessoResposta',
        ),
        migrations.RemoveField(
            model_name='analiseprocesso',
            name='portaria',
        ),
        migrations.AddField(
            model_name='semana',
            name='portaria',
            field=models.CharField(choices=[('SV', 'SV'), ('OIVA', 'OIVA'), ('PP', 'PP')], default='SV', max_length=4, null=True),
        ),
    ]
